included:
  - Package.swift
  - Sources
  - Tests
  - App

excluded:
  - .build
  - .swiftpm
  - DerivedData

disabled_rules:
  - file_length
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - type_body_length

opt_in_rules:
  - duplicate_imports
  - sorted_imports

reporter: "xcode"
