#!/usr/bin/env python3

"""Rebuild Noonmark's canonical AppIcon SVG from its committed PNG reference."""

from __future__ import annotations

import argparse
import colorsys
import hashlib
import html
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
REFERENCE_SOURCE = (
    REPOSITORY_ROOT
    / "docs"
    / "assets"
    / "brand"
    / "noonmark-logo-reference.png"
)
REFERENCE_SHA256 = (
    "9130bd34e01eb56c5637f28f04acfbc2ac541bf3422467f43796b8fe93d092a3"
)
EXPECTED_CANDIDATE_PATHS = 2_867
EXPECTED_SYMBOL_PATHS = 1_645


SVG_PREFIX = """<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024" role="img" aria-labelledby="title description">
  <title id="title">Noonmark hand-painted sundial app icon</title>
  <desc id="description">
    A hand-painted black and muted-gold sundial on a warm white macOS icon tile.
  </desc>
  <!-- Generated by scripts/vectorize-app-icon-source.py from the committed PNG reference. -->
  <defs>
    <linearGradient id="rim" x1="0" y1="100" x2="0" y2="924" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#FDF9F4"/>
      <stop offset="0.68" stop-color="#F3ECE5"/>
      <stop offset="1" stop-color="#E8DED4"/>
    </linearGradient>
    <linearGradient id="face" x1="166" y1="120" x2="858" y2="912" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#FFFCF8"/>
      <stop offset="0.46" stop-color="#FAF4EF"/>
      <stop offset="1" stop-color="#F5EEE8"/>
    </linearGradient>
    <linearGradient id="edge" x1="0" y1="100" x2="0" y2="924" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#EEE8E1"/>
      <stop offset="0.72" stop-color="#DED5CB"/>
      <stop offset="1" stop-color="#CFC4B8"/>
    </linearGradient>
    <clipPath id="tileBounds" clipPathUnits="userSpaceOnUse">
      <rect x="100" y="100" width="824" height="824" rx="188"/>
    </clipPath>
    <clipPath id="symbolBounds" clipPathUnits="userSpaceOnUse">
      <rect
        x="167.600887"
        y="179.476718"
        width="689.711752"
        height="685.144124"
      />
    </clipPath>
  </defs>

  <g clip-path="url(#tileBounds)">
    <rect
      x="100"
      y="106"
      width="824"
      height="818"
      rx="188"
      fill="url(#rim)"
      stroke="url(#edge)"
      stroke-width="2"
    />
    <rect
      x="100"
      y="100"
      width="824"
      height="812"
      rx="188"
      fill="url(#face)"
      stroke="#DED7CF"
      stroke-width="1.5"
    />
    <rect
      x="103"
      y="103"
      width="818"
      height="806"
      rx="185"
      fill="none"
      stroke="#FFFFFF"
      stroke-opacity="0.72"
      stroke-width="3"
    />
  </g>

  <g
    clip-path="url(#symbolBounds)"
  >
    <g
      transform="matrix(0.913525498891 0 0 0.913525498891 -60.780487804878 -37.942350332594)"
      shape-rendering="geometricPrecision"
    >
"""

SVG_SUFFIX = """    </g>
  </g>
</svg>
"""


def source_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def require_reference_source(path: Path) -> str:
    if not path.is_file():
        raise RuntimeError(f"missing AppIcon PNG reference: {path}")
    digest = source_sha256(path)
    if digest != REFERENCE_SHA256:
        raise RuntimeError(
            "AppIcon PNG reference SHA-256 mismatch: "
            f"expected {REFERENCE_SHA256}, got {digest}"
        )
    return digest


def trace_png(source: Path, candidate: Path) -> None:
    try:
        import vtracer
    except ModuleNotFoundError as error:
        raise RuntimeError(
            "vtracer 0.6.15 is required; follow "
            "docs/engineering/png-to-vector-workflow.md"
        ) from error

    vtracer.convert_image_to_svg_py(
        image_path=str(source),
        out_path=str(candidate),
        colormode="color",
        hierarchical="stacked",
        mode="spline",
        filter_speckle=1,
        color_precision=8,
        layer_difference=8,
        corner_threshold=60,
        length_threshold=2.0,
        max_iterations=10,
        splice_threshold=45,
        path_precision=4,
    )


def local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def is_symbol_color(fill: str) -> bool:
    if not fill.startswith("#") or len(fill) != 7:
        return False

    try:
        red, green, blue = (
            int(fill[index : index + 2], 16) for index in (1, 3, 5)
        )
    except ValueError:
        return False

    hue, saturation, _ = colorsys.rgb_to_hsv(
        red / 255,
        green / 255,
        blue / 255,
    )
    dark_ink = (
        max(red, green, blue) <= 175
        and max(red, green, blue) - min(red, green, blue) <= 55
    )
    warm_gold = (
        0.065 <= hue <= 0.16
        and saturation >= 0.28
        and red >= 105
        and red > green > blue
    )
    return dark_ink or warm_gold


def extract_symbol_paths(candidate: Path) -> list[str]:
    try:
        root = ET.parse(candidate).getroot()
    except (OSError, ET.ParseError) as error:
        raise RuntimeError(f"invalid VTracer candidate: {candidate}") from error

    view_box = root.attrib.get("viewBox", "").split()
    dimensions_match = (
        root.attrib.get("width") == "1254"
        and root.attrib.get("height") == "1254"
    )
    if view_box and view_box != ["0", "0", "1254", "1254"]:
        raise RuntimeError(
            f"unexpected VTracer candidate viewBox: {' '.join(view_box)}"
        )
    if not view_box and not dimensions_match:
        raise RuntimeError(
            "VTracer candidate must use a 1254 × 1254 source canvas"
        )

    candidates = [
        element for element in root.iter() if local_name(element.tag) == "path"
    ]
    if len(candidates) != EXPECTED_CANDIDATE_PATHS:
        raise RuntimeError(
            "unexpected VTracer candidate path count: "
            f"expected {EXPECTED_CANDIDATE_PATHS}, got {len(candidates)}"
        )

    retained: list[str] = []
    for path in candidates:
        fill = path.attrib.get("fill", "")
        if not is_symbol_color(fill):
            continue

        path_data = path.attrib.get("d")
        transform = path.attrib.get("transform")
        if not path_data or not transform:
            raise RuntimeError("retained VTracer path lacks d or transform")
        retained.append(
            '    <path d="'
            f'{html.escape(path_data, quote=True)}" '
            f'fill="{html.escape(fill, quote=True)}" '
            f'transform="{html.escape(transform, quote=True)}"/>'
        )

    if len(retained) != EXPECTED_SYMBOL_PATHS:
        raise RuntimeError(
            "unexpected retained symbol path count: "
            f"expected {EXPECTED_SYMBOL_PATHS}, got {len(retained)}"
        )
    return retained


def render_canonical_svg(symbol_paths: list[str]) -> str:
    return SVG_PREFIX + "\n".join(symbol_paths) + "\n" + SVG_SUFFIX


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=REFERENCE_SOURCE)
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--candidate-svg",
        type=Path,
        help="reuse an existing VTracer candidate instead of tracing again",
    )
    parser.add_argument("--verify-source-only", action="store_true")
    arguments = parser.parse_args()

    try:
        digest = require_reference_source(arguments.input)
        if arguments.verify_source_only:
            print(f"Verified AppIcon PNG reference SHA-256: {digest}")
            return 0
        if arguments.output is None:
            parser.error("--output is required unless --verify-source-only is used")

        if arguments.candidate_svg is not None:
            symbol_paths = extract_symbol_paths(arguments.candidate_svg)
        else:
            with tempfile.TemporaryDirectory(
                prefix="noonmark-app-icon-vector-"
            ) as temporary_directory:
                candidate = Path(temporary_directory) / "candidate.svg"
                trace_png(arguments.input, candidate)
                symbol_paths = extract_symbol_paths(candidate)

        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(
            render_canonical_svg(symbol_paths),
            encoding="utf-8",
        )
    except (OSError, RuntimeError) as error:
        print(error, file=sys.stderr)
        return 1

    print(
        f"Wrote {arguments.output} with {len(symbol_paths)} retained spline paths"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
